stages:
  - build
  - upload
  - release

variables:
  PACKAGE_VERSION: "$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')"
  DMG_BINARY: "GitDock-${PACKAGE_VERSION}.dmg"


build-windows:
  stage: build
  only:
    - tags
  tags:
    - windows
    - shared-windows
    - windows-1809
  before_script:
    - cup nodejs.install -y
  script:
    - npm install
    - npm run make -- --platform=win32
  artifacts:
    paths:
      - out/make

build-mac-and-linux:
  stage: build
  only:
    - tags
  tags:
    - self-hosted
  script:
    - npm install
    - brew install fakeroot && brew install dpkg
    - npm run make -- --platform=darwin && npm run make -- --platform=linux
  artifacts:
    paths:
      - out/make

upload:
  stage: upload
  needs:
    - build
  image: curlimages/curl:latest
  dependencies:
    - build-mac-and-linux
  only:
    - tags
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file out/make/${DMG_BINARY} ${PACKAGE_REGISTRY_URL}/${DMG_BINARY}

release:
  stage: release
  needs:
    - build
  image: registry.gitlab.com/gitlab-org/release-cli
  only:
    - tags
  except:
    - branches
  script:
    - VERSION="$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')"
    - release-cli create --name "v$VERSION" --tag-name "v$VERSION"
