stages:
  - version
  - build
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/gitdock"

release-version-creation:
  stage: version
  script:
    - echo "VERSION=$(sed -n -e \"s,^\s\+VERSION = '\([0-9]\+\.[0-9]\+\.[0-9]\+\)'.freeze,\1,p\" lib/GEM_NAME/version.rb)" > version.env
  artifacts:
    reports:
      dotenv: version.env

build-windows:
  stage: build
  only:
    - tags
  tags:
    - windows
    - shared-windows
    - windows-1809
  before_script:
    - cup nodejs.install -y
  script:
    - npm install
    - npm run make -- --platform=win32
  artifacts:
    paths:
      - out/make

build-mac-and-linux:
  stage: build
  only:
    - tags
  tags:
    - self-hosted
  script:
    - npm install
    - brew install fakeroot && brew install dpkg
    - npm run make -- --platform=darwin && npm run make -- --platform=linux
  artifacts:
    paths:
      - out/make

upload:
  stage: upload
  needs:
    - job: build-mac-and-linux
      artifacts: true
    - job: build-windows
      artifacts: true
    - job: release-version-creation
      artifacts: true
  image: curlimages/curl:latest
  only:
    - tags
  before_script:
    - VERSION="$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')"
  script:
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file out/make/GitDock-${VERSION}.dmg ${PACKAGE_REGISTRY_URL}/${VERSION}/GitDock.dmg
    - |
      curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file out/make/squirrel.windows/x64/GitDock.exe ${PACKAGE_REGISTRY_URL}/${VERSION}/GitDock.exe

release-test:
  stage: release
  needs:
    - job: build-mac-and-linux
      artifacts: true
    - job: build-windows
      artifacts: true
    - job: release-version-creation
      artifacts: true
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  only:
    - tags
  except:
    - branches
  script:
    - echo "v$VERSION"
    - echo "${PACKAGE_REGISTRY_URL}/${VERSION}/GitDock.dmg"}
  release:
      name: "v$VERSION"
      tag_name: "v$VERSION"
      description: "v$VERSION"
      assets:
        links:
          - name: "MacOS"
            url: "${PACKAGE_REGISTRY_URL}/${VERSION}/GitDock.dmg"
          - name: "Windows"
            url: "${PACKAGE_REGISTRY_URL}/${VERSION}/GitDock.exe"
