stages:
  - release
  - build

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli
  only:
    - tags
  except:
    - branches
  script:
    - VERSION="$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed 's/[version:,\",]//g' | tr -d '[[:space:]]')"
    - release-cli create --name "v$VERSION" --tag-name "v$VERSION"

build-windows:
  stage: build
  needs:
    - release
  only:
    - tags
  tags:
    - windows
    - shared-windows
    - windows-1809
  before_script:
    - cup nodejs.install -y
  script:
    - npm install
    - npm run make -- --platform=win32
  artifacts:
    paths:
      - out/make

build-mac-and-linux:
  stage: build
  needs:
    - release
  only:
    - tags
  tags:
    - self-hosted
  script:
    - npm install
    - brew install fakeroot && brew install dpkg
    - npm run make -- --platform=darwin && npm run make -- --platform=linux
  artifacts:
    paths:
      - out/make
