version: 2.1
orbs:
  node: circleci/node@4.1
jobs:
  build-and-test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages
      - run: 
          name: Get environment ready
          command: sudo apt update && sudo apt install rpm -y
      - run:
          name: Run make
          command: npm run make
      - store_artifacts:
          path: ~/project/out/make
          

workflows:
  sample: 
    jobs:
      - build-and-test
