module.exports = {
  query: "'query'",
  state: "'state'",
  sort: "'sort'",
  allLabel: "'all'",
  allText: "'All'",
  assignedLabel: "'assigned_to_me'",
  assignedText: "'Assigned'",
  createdLabel: "'created_by_me'",
  createdText: "'Created'",
  openedLabel: "'opened'",
  openedText: "'Open'",
  closedLabel: "'closed'",
  closedText: "'Closed'",
  recentlyUpdatedLabel: "'updated_at'",
  recentlyUpdatedText: "'Sort by recently updated'",
  recentlyCreatedLabel: "'created_at'",
  recentlyCreatedText: "'Sort by recently created'",
  dueDateLabel: "'due_date&sort=asc'",
  dueDateText: "'Sort by due date'",
  reviewedLabel: "'review_requests_for_me'",
  reviewedText: "'Reviewed'",
  approvedLabel: "'approved_by_me'",
  approvedText: "'Approved'",
  mergedLabel: "'merged'",
  mergedText: "'Merged'",
  approvalLabel: "'approval_rule_for_me'",
  approvalText: "'Approval rules'",
};
